version: '2'
services:
  server:
    image: jonhelgi/tictactoe
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PORT=3000
    ports:
      - 8080:8080
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    environment:
      - POSTGRES_PASSWORD: 'mysecretpassword'
      - POSTGRES_USER: 'postgres'
    image: postgres
