version: '2'
services:
  server:
    image: jongrjon/tictactoe
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PORT=3000
      - NODE_ENV=prod
    ports:
      - 8080:8080
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    image: postgres
    ports:
      - 5432:5432
